import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { userInfo } from "node:os";
import { join } from "node:path";
import { type CommandRunner, nodeRunner } from "../../daemon/autostart/runner.js";
import { type ManagedPaths, readManagedState, writeManagedState } from "./pg-paths.js";
import type { RuntimePaths } from "./pg-runtime-provider.js";

// ─── Managed block delimiters ────────────────────────────────────────────────

const BLOCK_START = "# >>> memkin managed >>>";
const BLOCK_END = "# <<< memkin managed <<<";

// ─── Public interface ─────────────────────────────────────────────────────────

export interface PgSupervisorDeps {
  runtime: RuntimePaths;
  paths: ManagedPaths;
  runner?: CommandRunner; // default: nodeRunner
  bootstrapUser?: string; // default: process.env.USER ?? userInfo().username
}

export interface WaitReadyOptions {
  /** How often to poll pg_isready (default: 250 ms) */
  pollIntervalMs?: number;
  /** Total timeout before throwing (default: 15 000 ms) */
  timeoutMs?: number;
}

export interface PgSupervisor {
  ensureCluster(): Promise<void>;
  start(): Promise<void>;
  startWithStaleRecovery(): Promise<void>;
  waitReady(opts?: WaitReadyOptions): Promise<void>;
  bootstrapRoles(): Promise<void>;
  finalizeHba(): Promise<void>;
  ensureUp(): Promise<void>;
  status(): Promise<"running" | "stopped">;
  restartIfDown(waitReadyOpts?: WaitReadyOptions): Promise<boolean>;
  stop(): Promise<void>;
  dispose(): void;
}

// ─── Factory ──────────────────────────────────────────────────────────────────

export function createPgSupervisor(deps: PgSupervisorDeps): PgSupervisor {
  const { runtime, paths } = deps;
  const runner: CommandRunner = deps.runner ?? nodeRunner;
  const bootstrapUser: string = deps.bootstrapUser ?? process.env.USER ?? userInfo().username;

  // ── Private helpers ────────────────────────────────────────────────────────

  /**
   * Write (or replace) the memkin-managed block inside postgresql.conf.
   * If the file already contains the managed block, it is replaced in-place.
   * If the file does not exist yet, it is created with only the managed block.
   * Non-managed content outside the block is preserved.
   */
  function writeManagedConf(): void {
    const confPath = join(paths.pgdata, "postgresql.conf");

    const managedBlock = [
      BLOCK_START,
      "# Auto-generated by memkin — do not edit manually between these markers.",
      "listen_addresses = ''",
      `unix_socket_directories = '${paths.socketDir}'`,
      "unix_socket_permissions = 0700",
      `port = ${paths.fixedPort}`,
      BLOCK_END,
    ].join("\n");

    if (existsSync(confPath)) {
      const existing = readFileSync(confPath, "utf8");
      const startIdx = existing.indexOf(BLOCK_START);
      const endIdx = existing.indexOf(BLOCK_END);

      if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
        // Replace existing managed block
        const before = existing.slice(0, startIdx);
        const after = existing.slice(endIdx + BLOCK_END.length);
        writeFileSync(confPath, `${before}${managedBlock}${after}`, "utf8");
      } else {
        // Append managed block (no prior block found)
        const separator = existing.endsWith("\n") ? "\n" : "\n\n";
        writeFileSync(confPath, `${existing}${separator}${managedBlock}\n`, "utf8");
      }
    } else {
      // New file — write managed block only
      writeFileSync(confPath, `${managedBlock}\n`, "utf8");
    }
  }

  /**
   * Write the temporary (phase-1) pg_hba.conf.
   * Only allows the bootstrap OS user via local UNIX socket with trust auth.
   * The final restrictive HBA is applied in a later task (Task 8).
   */
  function writeTempHba(): void {
    const hbaPath = join(paths.pgdata, "pg_hba.conf");
    const content = [
      "# Temporary HBA — managed by memkin (phase 1). DO NOT EDIT.",
      "# Final restrictive HBA is applied after bootstrap roles are created.",
      `local all ${bootstrapUser} trust`,
      "",
    ].join("\n");
    writeFileSync(hbaPath, content, "utf8");
  }

  /**
   * Build a psql argv array for running a single SQL command.
   * All connections go through the UNIX socket (host = socketDir).
   */
  function psqlArgs(db: string, sql: string, opts: { tuplesOnly?: boolean } = {}): string[] {
    const psql = join(runtime.bin, "psql");
    const argv = [
      psql,
      "-h",
      paths.socketDir,
      "-p",
      String(paths.fixedPort),
      "-U",
      bootstrapUser,
      "-d",
      db,
      "-v",
      "ON_ERROR_STOP=1",
    ];
    if (opts.tuplesOnly) {
      argv.push("-tAc", sql);
    } else {
      argv.push("-c", sql);
    }
    return argv;
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  return {
    async ensureCluster(): Promise<void> {
      const pgVersionFile = join(paths.pgdata, "PG_VERSION");
      const clusterExists = existsSync(pgVersionFile);

      if (!clusterExists) {
        // Run initdb to initialise the cluster
        const result = await runner.run([
          runtime.initdb,
          "-D",
          paths.pgdata,
          "-U",
          bootstrapUser,
          "--auth=trust",
          "--encoding=UTF8",
        ]);

        if (result.code !== 0) {
          throw new Error(
            `initdb failed (exit ${result.code}) for pgdata=${paths.pgdata}: ${result.stderr}`,
          );
        }

        // In real usage initdb creates pgdata; for fake-runner paths ensure the
        // directory exists so the conf-writes below succeed.
        mkdirSync(paths.pgdata, { recursive: true });
      }

      // Always (re-)create the socket dir with mode 0700
      mkdirSync(paths.socketDir, { recursive: true, mode: 0o700 });

      // Write / replace the managed postgresql.conf block (idempotent)
      writeManagedConf();

      // Write the temporary pg_hba.conf ONLY when not yet bootstrapped.
      // After bootstrap, the HBA has been finalized to the restrictive version.
      // Re-writing the temp HBA would loosen security back to bootstrap-user-trust.
      // Bootstrapped ⇔ managed-state file exists.
      if (readManagedState(paths) === null) {
        // The temp HBA (bootstrap-user trust) is only ever active before finalizeHba.
        // Its containment relies on listen_addresses='' (no TCP) + the 0700 private socket dir —
        // do NOT weaken either without revisiting this bootstrap-window exposure.
        writeTempHba();
      }
    },

    async start(): Promise<void> {
      const logPath = join(paths.pgdata, "postmaster.log");
      const result = await runner.run([
        runtime.pgCtl,
        "start",
        "-D",
        paths.pgdata,
        "-l",
        logPath,
        "-w",
        "-o",
        `-p ${paths.fixedPort}`,
      ]);
      if (result.code !== 0) {
        throw new Error(
          `pg_ctl start failed (exit ${result.code}), log=${logPath}: ${result.stderr}`,
        );
      }
    },

    async waitReady(opts: WaitReadyOptions = {}): Promise<void> {
      const pollIntervalMs = opts.pollIntervalMs ?? 250;
      const timeoutMs = opts.timeoutMs ?? 15_000;
      const deadline = Date.now() + timeoutMs;

      while (Date.now() < deadline) {
        const result = await runner.run([
          runtime.pgIsReady,
          "-h",
          paths.socketDir,
          "-p",
          String(paths.fixedPort),
        ]);
        if (result.code === 0) return;
        await new Promise<void>((resolve) => setTimeout(resolve, pollIntervalMs));
      }

      throw new Error(
        `pg_isready timeout after ${timeoutMs}ms: Postgres did not become ready (socketDir=${paths.socketDir}, port=${paths.fixedPort})`,
      );
    },

    async bootstrapRoles(): Promise<void> {
      // (a) Create memkin role — idempotent via DO block
      const roleResult = await runner.run(
        psqlArgs(
          "postgres",
          `DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='memkin') THEN CREATE ROLE memkin LOGIN; END IF; END $$;`,
        ),
      );
      if (roleResult.code !== 0) {
        throw new Error(`psql CREATE ROLE failed (exit ${roleResult.code}): ${roleResult.stderr}`);
      }

      // (b) Check if the memkin database already exists
      const dbCheckResult = await runner.run(
        psqlArgs("postgres", `SELECT 1 FROM pg_database WHERE datname='memkin'`, {
          tuplesOnly: true,
        }),
      );
      if (dbCheckResult.code !== 0) {
        throw new Error(
          `psql db-existence check failed (exit ${dbCheckResult.code}): ${dbCheckResult.stderr}`,
        );
      }

      // Only create the database if it does not exist yet
      if (dbCheckResult.stdout.trim() === "") {
        const createDbResult = await runner.run(
          psqlArgs("postgres", `CREATE DATABASE memkin OWNER memkin`),
        );
        if (createDbResult.code !== 0) {
          throw new Error(
            `psql CREATE DATABASE failed (exit ${createDbResult.code}): ${createDbResult.stderr}`,
          );
        }
      }

      // (c) Create extensions in the memkin database
      const extResult = await runner.run(
        psqlArgs(
          "memkin",
          `CREATE EXTENSION IF NOT EXISTS vector; CREATE EXTENSION IF NOT EXISTS pg_trgm;`,
        ),
      );
      if (extResult.code !== 0) {
        throw new Error(
          `psql CREATE EXTENSION failed (exit ${extResult.code}): ${extResult.stderr}`,
        );
      }
    },

    async finalizeHba(): Promise<void> {
      const hbaPath = join(paths.pgdata, "pg_hba.conf");
      const finalHba = [
        "# memkin final HBA — managed",
        "local   memkin   memkin   trust",
        "local   all       all       reject",
        "host    all       all       all     reject",
        "",
      ].join("\n");
      writeFileSync(hbaPath, finalHba, "utf8");

      const result = await runner.run([runtime.pgCtl, "reload", "-D", paths.pgdata]);
      if (result.code !== 0) {
        throw new Error(`pg_ctl reload failed (exit ${result.code}): ${result.stderr}`);
      }
    },

    async status(): Promise<"running" | "stopped"> {
      const result = await runner.run([runtime.pgCtl, "status", "-D", paths.pgdata]);
      return result.code === 0 ? "running" : "stopped";
    },

    async startWithStaleRecovery(): Promise<void> {
      const logPath = join(paths.pgdata, "postmaster.log");
      const startArgv = [
        runtime.pgCtl,
        "start",
        "-D",
        paths.pgdata,
        "-l",
        logPath,
        "-w",
        "-o",
        `-p ${paths.fixedPort}`,
      ];

      const first = await runner.run(startArgv);
      if (first.code === 0) return;

      // Start failed — check for stale postmaster.pid
      const pidFile = join(paths.pgdata, "postmaster.pid");
      if (!existsSync(pidFile)) {
        throw new Error(
          `pg_ctl start failed (exit ${first.code}), log=${logPath}: ${first.stderr}`,
        );
      }

      // Read PID from first line
      const pidLine = readFileSync(pidFile, "utf8").split("\n")[0].trim();
      const pid = Number(pidLine);

      // Check if process is actually alive
      let alive = true;
      if (!Number.isNaN(pid) && pid > 0) {
        try {
          process.kill(pid, 0);
        } catch (err: unknown) {
          if ((err as NodeJS.ErrnoException).code === "ESRCH") {
            alive = false;
          } else {
            // EPERM means process exists but we can't signal it — treat as alive
            alive = true;
          }
        }
      }

      if (!alive) {
        // Remove stale pid file and retry
        rmSync(pidFile, { force: true });
        const retry = await runner.run(startArgv);
        if (retry.code !== 0) {
          throw new Error(
            `pg_ctl start failed after stale pid removal (exit ${retry.code}), log=${logPath}: ${retry.stderr}`,
          );
        }
        return;
      }

      // Process is still alive — original error stands
      throw new Error(`pg_ctl start failed (exit ${first.code}), log=${logPath}: ${first.stderr}`);
    },

    async ensureUp(): Promise<void> {
      const bootstrapped = readManagedState(paths) !== null;

      // Initialise cluster if needed; refresh conf; write temp HBA only if !bootstrapped
      await this.ensureCluster();

      const currentStatus = await this.status();
      if (currentStatus !== "running") {
        await this.startWithStaleRecovery();
        await this.waitReady();
      }

      if (!bootstrapped) {
        await this.bootstrapRoles();
        await this.finalizeHba();
        writeManagedState(paths, {
          pgdata: paths.pgdata,
          fixedPort: paths.fixedPort,
          socketDir: paths.socketDir,
          runtimeRoot: runtime.root,
          pgVersion: runtime.pgMajor,
          pgCtlPath: runtime.pgCtl,
          logPath: join(paths.pgdata, "postmaster.log"),
        });
      }
    },

    async restartIfDown(waitReadyOpts?: WaitReadyOptions): Promise<boolean> {
      const currentStatus = await this.status();
      if (currentStatus === "running") return false;
      await this.startWithStaleRecovery();
      await this.waitReady(waitReadyOpts);
      return true;
    },

    async stop(): Promise<void> {
      // Tolerate "not running" — pg_ctl stop returns non-zero when already stopped.
      await runner.run([runtime.pgCtl, "stop", "-D", paths.pgdata, "-m", "fast"]);
    },

    dispose(): void {
      // No internal timer or monitor to clean up yet (recovery loop is a separate
      // module added in a later task). Per spec §4d, dispose MUST NOT stop the
      // cluster — it only stops internal monitoring resources owned by this object.
      // This is intentionally a no-op.
    },
  };
}
