import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { userInfo } from "node:os";
import { join } from "node:path";
import { type CommandRunner, nodeRunner } from "../../daemon/autostart/runner.js";
import type { ManagedPaths } from "./pg-paths.js";
import type { RuntimePaths } from "./pg-runtime-provider.js";

// ─── Managed block delimiters ────────────────────────────────────────────────

const BLOCK_START = "# >>> memoark managed >>>";
const BLOCK_END = "# <<< memoark managed <<<";

// ─── Public interface ─────────────────────────────────────────────────────────

export interface PgSupervisorDeps {
  runtime: RuntimePaths;
  paths: ManagedPaths;
  runner?: CommandRunner; // default: nodeRunner
  bootstrapUser?: string; // default: process.env.USER ?? userInfo().username
}

export interface PgSupervisor {
  ensureCluster(): Promise<void>;
  // start / waitReady / bootstrapRoles / finalizeHba / ensureUp /
  // status / restartIfDown / stop / dispose — added in later tasks
}

// ─── Factory ──────────────────────────────────────────────────────────────────

export function createPgSupervisor(deps: PgSupervisorDeps): PgSupervisor {
  const { runtime, paths } = deps;
  const runner: CommandRunner = deps.runner ?? nodeRunner;
  const bootstrapUser: string =
    deps.bootstrapUser ?? process.env.USER ?? userInfo().username;

  // ── Private helpers ────────────────────────────────────────────────────────

  /**
   * Write (or replace) the memoark-managed block inside postgresql.conf.
   * If the file already contains the managed block, it is replaced in-place.
   * If the file does not exist yet, it is created with only the managed block.
   * Non-managed content outside the block is preserved.
   */
  function writeManagedConf(): void {
    const confPath = join(paths.pgdata, "postgresql.conf");

    const managedBlock = [
      BLOCK_START,
      "# Auto-generated by memoark — do not edit manually between these markers.",
      "listen_addresses = ''",
      `unix_socket_directories = '${paths.socketDir}'`,
      "unix_socket_permissions = 0700",
      `port = ${paths.fixedPort}`,
      BLOCK_END,
    ].join("\n");

    if (existsSync(confPath)) {
      const existing = readFileSync(confPath, "utf8");
      const startIdx = existing.indexOf(BLOCK_START);
      const endIdx = existing.indexOf(BLOCK_END);

      if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
        // Replace existing managed block
        const before = existing.slice(0, startIdx);
        const after = existing.slice(endIdx + BLOCK_END.length);
        writeFileSync(confPath, `${before}${managedBlock}${after}`, "utf8");
      } else {
        // Append managed block (no prior block found)
        const separator = existing.endsWith("\n") ? "\n" : "\n\n";
        writeFileSync(confPath, `${existing}${separator}${managedBlock}\n`, "utf8");
      }
    } else {
      // New file — write managed block only
      writeFileSync(confPath, `${managedBlock}\n`, "utf8");
    }
  }

  /**
   * Write the temporary (phase-1) pg_hba.conf.
   * Only allows the bootstrap OS user via local UNIX socket with trust auth.
   * The final restrictive HBA is applied in a later task (Task 8).
   */
  function writeTempHba(): void {
    const hbaPath = join(paths.pgdata, "pg_hba.conf");
    const content = [
      "# Temporary HBA — managed by memoark (phase 1). DO NOT EDIT.",
      "# Final restrictive HBA is applied after bootstrap roles are created.",
      `local all ${bootstrapUser} trust`,
      "",
    ].join("\n");
    writeFileSync(hbaPath, content, "utf8");
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  return {
    async ensureCluster(): Promise<void> {
      const pgVersionFile = join(paths.pgdata, "PG_VERSION");
      const clusterExists = existsSync(pgVersionFile);

      if (!clusterExists) {
        // Run initdb to initialise the cluster
        const result = await runner.run([
          runtime.initdb,
          "-D",
          paths.pgdata,
          "-U",
          bootstrapUser,
          "--auth=trust",
          "--encoding=UTF8",
        ]);

        if (result.code !== 0) {
          throw new Error(
            `initdb failed (exit ${result.code}) for pgdata=${paths.pgdata}: ${result.stderr}`,
          );
        }

        // In real usage initdb creates pgdata; for fake-runner paths ensure the
        // directory exists so the conf-writes below succeed.
        mkdirSync(paths.pgdata, { recursive: true });
      }

      // Always (re-)create the socket dir with mode 0700
      mkdirSync(paths.socketDir, { recursive: true, mode: 0o700 });

      // Write / replace the managed postgresql.conf block (idempotent)
      writeManagedConf();

      // Write the temporary pg_hba.conf (idempotent overwrite)
      writeTempHba();
    },
  };
}
