import { describe, expect, it } from "vitest";
import { parse } from "yaml";
import { buildConfigObject, generateConfigYaml } from "../../src/setup/generate-config.js";

const OPENAI_API_KEY_PLACEHOLDER = "$" + "{OPENAI_API_KEY}";
const FEISHU_APP_ID_PLACEHOLDER = "$" + "{FEISHU_APP_ID}";
const FEISHU_APP_SECRET_PLACEHOLDER = "$" + "{FEISHU_APP_SECRET}";
const DATABASE_URL_PLACEHOLDER = "$" + "{DATABASE_URL}";

describe("generate setup config", () => {
  it("generates YAML with the expected top-level sections", () => {
    const yaml = generateConfigYaml({});

    expect(yaml).toContain("# Generated by 'memoark init'");
    expect(yaml).toContain("privacy:");
    expect(yaml).toContain("llm:");
    expect(yaml).toContain("sources:");
    expect(yaml).toContain("embedding:");
    expect(yaml).toContain("server:");
    expect(yaml).toContain("mcp:");
    expect(yaml).toContain("http:");
  });

  it("preserves environment variable placeholders", () => {
    const yaml = generateConfigYaml({
      llm: {
        provider: "openai",
        model: "gpt-4o-mini",
        api_key: OPENAI_API_KEY_PLACEHOLDER,
      },
      sources: {
        "claude-code": { enabled: true },
        feishu: {
          enabled: true,
          app_id: FEISHU_APP_ID_PLACEHOLDER,
          app_secret: FEISHU_APP_SECRET_PLACEHOLDER,
        },
      },
    });

    expect(yaml).toContain(OPENAI_API_KEY_PLACEHOLDER);
    expect(yaml).toContain(FEISHU_APP_ID_PLACEHOLDER);
    expect(yaml).toContain(FEISHU_APP_SECRET_PLACEHOLDER);
  });

  it("uses Ollama embedding defaults when selected", () => {
    const config = buildConfigObject({
      embedding: { provider: "ollama" },
    });

    expect(config.embedding).toEqual({
      provider: "ollama",
      model: "nomic-embed-text",
      dimensions: 768,
    });
  });

  it("emits parseable YAML", () => {
    const parsed = parse(
      generateConfigYaml({
        llm: { provider: "anthropic", model: "claude-3-haiku-20240307" },
        sources: { codex: { enabled: true } },
      }),
    );

    expect(parsed.llm.provider).toBe("anthropic");
    expect(parsed.sources.codex.enabled).toBe(true);
  });

  it("defaults to pglite with data_dir when no store config given", () => {
    const config = buildConfigObject({});
    expect(config.store.engine).toBe("pglite");
    expect(config.store.data_dir).toBe("~/.memoark/data");
    expect(config.store.database_url).toBeUndefined();
  });

  it("emits postgres engine with ${DATABASE_URL} placeholder by default", () => {
    const config = buildConfigObject({ store: { engine: "postgres" } });
    expect(config.store.engine).toBe("postgres");
    expect(config.store.database_url).toBe(DATABASE_URL_PLACEHOLDER);
    expect(config.store.data_dir).toBeUndefined();
  });

  it("preserves explicit database_url and pool_size", () => {
    const config = buildConfigObject({
      store: {
        engine: "postgres",
        database_url: DATABASE_URL_PLACEHOLDER,
        pool_size: 20,
      },
    });
    expect(config.store.database_url).toBe(DATABASE_URL_PLACEHOLDER);
    expect(config.store.pool_size).toBe(20);
  });

  it("generates parseable YAML with postgres store fields", () => {
    const yaml = generateConfigYaml({ store: { engine: "postgres" } });
    const parsed = parse(yaml);
    expect(parsed.store.engine).toBe("postgres");
    expect(parsed.store.database_url).toBe(DATABASE_URL_PLACEHOLDER);
  });

  // Part A — managed branch in buildStore
  it("buildConfigObject with engine managed: no data_dir, no database_url", () => {
    const config = buildConfigObject({ store: { engine: "managed" } });
    expect(config.store.engine).toBe("managed");
    expect(config.store.data_dir).toBeUndefined();
    expect(config.store.database_url).toBeUndefined();
  });

  it("buildConfigObject managed with runtime_dir round-trips through buildStore", () => {
    const config = buildConfigObject({
      store: { engine: "managed", managed: { runtime_dir: "/opt/pg" } },
    });
    expect(config.store.engine).toBe("managed");
    expect((config.store as { managed?: { runtime_dir?: string } }).managed?.runtime_dir).toBe(
      "/opt/pg",
    );
    expect(config.store.data_dir).toBeUndefined();
    expect(config.store.database_url).toBeUndefined();
  });

  // Part C — opt-in newInstallEngine
  it("buildConfigObject with newInstallEngine=managed and no explicit store.engine → managed", () => {
    const config = buildConfigObject({}, { newInstallEngine: "managed" });
    expect(config.store.engine).toBe("managed");
    expect(config.store.data_dir).toBeUndefined();
    expect(config.store.database_url).toBeUndefined();
  });

  it("buildConfigObject without opts (no newInstallEngine) → pglite (silent default unchanged)", () => {
    const config = buildConfigObject({});
    expect(config.store.engine).toBe("pglite");
    expect(config.store.data_dir).toBe("~/.memoark/data");
  });

  it("explicit store.engine=pglite is respected even when newInstallEngine=managed", () => {
    const config = buildConfigObject(
      { store: { engine: "pglite" } },
      { newInstallEngine: "managed" },
    );
    expect(config.store.engine).toBe("pglite");
    expect(config.store.data_dir).toBe("~/.memoark/data");
  });

  it("generateConfigYaml with newInstallEngine=managed produces managed store YAML", () => {
    const yaml = generateConfigYaml({}, { newInstallEngine: "managed" });
    const parsed = parse(yaml);
    expect(parsed.store.engine).toBe("managed");
    expect(parsed.store.data_dir).toBeUndefined();
    expect(parsed.store.database_url).toBeUndefined();
  });
});
