import { describe, expect, it } from "vitest";
import { parse } from "yaml";
import { buildConfigObject, generateConfigYaml } from "../../src/setup/generate-config.js";

const OPENAI_API_KEY_PLACEHOLDER = "$" + "{OPENAI_API_KEY}";
const FEISHU_APP_ID_PLACEHOLDER = "$" + "{FEISHU_APP_ID}";
const FEISHU_APP_SECRET_PLACEHOLDER = "$" + "{FEISHU_APP_SECRET}";

describe("generate setup config", () => {
  it("generates YAML with the expected top-level sections", () => {
    const yaml = generateConfigYaml({});

    expect(yaml).toContain("# Generated by 'memoark init'");
    expect(yaml).toContain("privacy:");
    expect(yaml).toContain("llm:");
    expect(yaml).toContain("sources:");
    expect(yaml).toContain("embedding:");
    expect(yaml).toContain("server:");
  });

  it("preserves environment variable placeholders", () => {
    const yaml = generateConfigYaml({
      llm: {
        provider: "openai",
        model: "gpt-4o-mini",
        api_key: OPENAI_API_KEY_PLACEHOLDER,
      },
      sources: {
        "claude-code": { enabled: true },
        feishu: {
          enabled: true,
          app_id: FEISHU_APP_ID_PLACEHOLDER,
          app_secret: FEISHU_APP_SECRET_PLACEHOLDER,
        },
      },
    });

    expect(yaml).toContain(OPENAI_API_KEY_PLACEHOLDER);
    expect(yaml).toContain(FEISHU_APP_ID_PLACEHOLDER);
    expect(yaml).toContain(FEISHU_APP_SECRET_PLACEHOLDER);
  });

  it("uses Ollama embedding defaults when selected", () => {
    const config = buildConfigObject({
      embedding: { provider: "ollama" },
    });

    expect(config.embedding).toEqual({
      provider: "ollama",
      model: "nomic-embed-text",
      dimensions: 768,
    });
  });

  it("emits parseable YAML", () => {
    const parsed = parse(
      generateConfigYaml({
        llm: { provider: "anthropic", model: "claude-3-haiku-20240307" },
        sources: { codex: { enabled: true } },
      }),
    );

    expect(parsed.llm.provider).toBe("anthropic");
    expect(parsed.sources.codex.enabled).toBe(true);
  });
});
